/**
 * Generates assets/tokens.css from a single seed colour.
 *
 * Material 3 Expressive, colour spec SPEC_2026, phone platform, standard
 * contrast. Both themes come out of the same DynamicScheme so light and dark
 * stay in step: change SEED here and every surface, badge and outline on the
 * wall follows.
 */
import {writeFileSync} from 'node:fs';
import {
  Hct,
  DynamicScheme,
  Variant,
  MaterialDynamicColors,
  argbFromHex,
  hexFromArgb,
} from '@ktibow/material-color-utilities-nightly';

const SEED = '#4444fe';
const SPEC_VERSION = '2026';

const ROLES = [
  'background', 'onBackground',
  'surface', 'surfaceDim', 'surfaceBright',
  'surfaceContainerLowest', 'surfaceContainerLow', 'surfaceContainer',
  'surfaceContainerHigh', 'surfaceContainerHighest',
  'onSurface', 'surfaceVariant', 'onSurfaceVariant',
  'inverseSurface', 'inverseOnSurface',
  'outline', 'outlineVariant', 'shadow', 'scrim', 'surfaceTint',
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'inversePrimary',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'primaryFixed', 'primaryFixedDim', 'onPrimaryFixed', 'onPrimaryFixedVariant',
  'secondaryFixed', 'secondaryFixedDim', 'onSecondaryFixed', 'onSecondaryFixedVariant',
  'tertiaryFixed', 'tertiaryFixedDim', 'onTertiaryFixed', 'onTertiaryFixedVariant',
];

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function scheme(isDark) {
  return new DynamicScheme({
    sourceColorHct: Hct.fromInt(argbFromHex(SEED)),
    variant: Variant.EXPRESSIVE,
    contrastLevel: 0,
    isDark,
    platform: 'phone',
    specVersion: SPEC_VERSION,
  });
}

function block(isDark, indent = '  ') {
  const s = scheme(isDark);
  return ROLES
    .map((role) => `${indent}--md-sys-color-${kebab(role)}: ${hexFromArgb(MaterialDynamicColors[role].getArgb(s))};`)
    .join('\n');
}

const light = block(false);
const dark = block(true);

const css = `/* Generated by tools/generate-tokens.mjs — do not edit by hand.
   Material 3 Expressive · colour spec ${SPEC_VERSION} · seed ${SEED} */

/* Light is the base palette. */
:root {
${light}
  color-scheme: light dark;
}

/* Viewers on "system" carry no data-theme stamp, so the media query has to
   cover them — guarded so an explicit light choice still beats a dark OS. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${dark}
  }
}

/* An explicit dark choice wins in the other direction. */
:root[data-theme="dark"] {
${dark}
}
`;

writeFileSync(new URL('../assets/tokens.css', import.meta.url), css);
console.log(`tokens.css written — Expressive / spec ${SPEC_VERSION} / seed ${SEED}`);
